export const defaultCloudinary = {
  sources: [
    "local",
    "url",
    "camera",
    "image_search",
    "google_drive",
    "facebook",
    "dropbox",
    "instagram",
    "shutterstock",
    "getty",
    "istock",
    "unsplash",
  ],
  showAdvancedOptions: true,
  cropping: false,
  multiple: true,
  defaultSource: "local",
  folder: "useCloudinary",
  styles: {
    palette: {
      window: "#10173a",
      sourceBg: "#20304b",
      windowBorder: "#7171d0",
      tabIcon: "#79f7ff",
      inactiveTabIcon: "#8e9fbf",
      menuIcons: "#cce8ff",
      link: "#72f1ff",
      action: "#5333ff",
      inProgress: "#00ffcc",
      complete: "#33ff00",
      error: "#cc3333",
      textDark: "#000000",
      textLight: "#ffffff",
    },
    fonts: {
      default: null,
      "'IBM Plex Sans', sans-serif": {
        url: "https://fonts.googleapis.com/css?family=IBM+Plex+Sans",
        active: true,
      },
    },
  },
};
